"""
ward_bias.py  (Sentinel AI)

Applies per-ward composite-AQI multipliers (alpha) to a single live city AQI,
fixing the coarse-grid problem where Open-Meteo returns near-identical AQI for
all Pune wards (~42 everywhere).

    ward_aqi = live_city_aqi * alpha

alpha values come from ward_bias_factors.json (generated by analyze_history.py
from 8 CPCB station histories via paired-hourly ratio).
Unknown wards fall back to alpha = 1.0 (safe no-op).

USAGE IN BACKEND:
    from ward_bias import apply_ward_bias, WARD_COORDS
    wards = apply_ward_bias(live_city_aqi, WARD_COORDS)
"""

import json
import os
from functools import lru_cache

_FACTORS_PATH = os.path.join(os.path.dirname(__file__), "ward_bias_factors.json")

# Pune ward centroids. Adjust to match your MapLibre marker coordinates.
WARD_COORDS = {
    "Revenue Colony Shivajinagar": (18.5308, 73.8475),
    "Bhosari": (18.6298, 73.8474),
    "Mhada Colony": (18.5000, 73.8200),
    "Savitribai Phule University": (18.4550, 73.8250),
    "Transport Nagar Nigdi": (18.6600, 73.7700),
    "Hadapsar": (18.5089, 73.9260),
    "MIT Kothrud": (18.5074, 73.8077),
    "Katraj Dairy": (18.4483, 73.8600),
}


@lru_cache(maxsize=1)
def load_factors(path: str = _FACTORS_PATH) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def get_alpha(ward_name: str) -> float:
    """Alpha for a ward; 1.0 if the ward isn't in the factors file."""
    entry = load_factors()["wards"].get(ward_name)
    return float(entry["alpha"]) if entry else 1.0


def apply_ward_bias(live_city_aqi: float, ward_coords: dict = None) -> list[dict]:
    """
    Scale one live city AQI across all wards.

    Args:
        live_city_aqi: current city-level AQI from the live fetcher.
        ward_coords:   {ward_name: (lat, lon)}. Defaults to WARD_COORDS.

    Returns:
        List of dicts ready for the /api/aqi/wards response.
    """
    if ward_coords is None:
        ward_coords = WARD_COORDS

    out = []
    for ward, (lat, lon) in ward_coords.items():
        alpha = get_alpha(ward)
        out.append({
            "ward": ward,
            "lat": lat,
            "lon": lon,
            "aqi": round(live_city_aqi * alpha, 1),
            "alpha": alpha,
            "city_aqi": live_city_aqi,
        })
    return out


if __name__ == "__main__":
    print("Test: live city AQI = 90\n")
    for r in sorted(apply_ward_bias(90), key=lambda x: -x["aqi"]):
        print(f"  {r['ward']:<30} alpha={r['alpha']:.3f}  AQI={r['aqi']}")
